version: "3"

tasks:
  generate:
    aliases:
    - gen
    desc: "Generate code from proto files"
    cmds:
    - protoc --proto_path=proto --go_out=./proto/gen/go --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go --go-grpc_opt=paths=source_relative subpub.proto
